DO
$$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'udp') THEN
      CREATE ROLE udp LOGIN PASSWORD 'udp';
   END IF;

   IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'airflow') THEN
      CREATE ROLE airflow LOGIN PASSWORD 'airflow';
   END IF;
END
$$;

SELECT 'CREATE DATABASE udp OWNER udp'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'udp')
\gexec

SELECT 'CREATE DATABASE airflow OWNER airflow'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'airflow')
\gexec

\connect udp

GRANT ALL PRIVILEGES ON DATABASE udp TO udp;
GRANT ALL PRIVILEGES ON SCHEMA public TO udp;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO udp;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO udp;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO udp;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO udp;
